language: bash
services: docker

env:
  - VERSION=9.0 VARIANT=jre9-slim
  - VERSION=9.0 VARIANT=jre9
  - VERSION=9.0 VARIANT=jre8-slim
  - VERSION=9.0 VARIANT=jre8-alpine
  - VERSION=9.0 VARIANT=jre8
  - VERSION=8.5 VARIANT=jre9-slim
  - VERSION=8.5 VARIANT=jre9
  - VERSION=8.5 VARIANT=jre8-slim
  - VERSION=8.5 VARIANT=jre8-alpine
  - VERSION=8.5 VARIANT=jre8
  - VERSION=8.0 VARIANT=jre8-slim
  - VERSION=8.0 VARIANT=jre8-alpine
  - VERSION=8.0 VARIANT=jre8
  - VERSION=8.0 VARIANT=jre7-slim
  - VERSION=8.0 VARIANT=jre7-alpine
  - VERSION=8.0 VARIANT=jre7
  - VERSION=7 VARIANT=jre8-slim
  - VERSION=7 VARIANT=jre8-alpine
  - VERSION=7 VARIANT=jre8
  - VERSION=7 VARIANT=jre7-slim
  - VERSION=7 VARIANT=jre7-alpine
  - VERSION=7 VARIANT=jre7

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - image="tomcat:$VERSION-$VARIANT"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
